//eight
console.log("------------------------");
console.log(5+3);
console.log("------------------------");
console.log(11-3);
console.log("------------------------");
console.log(2*4);
console.log("------------------------");
console.log(64/8);
